### ISSUE TITLE
Unable to install pygdbmi==0.7.4.2 ImportError: cannot import name 'POINTER'

### ISSUE THREAD

**Issue by asgeroverby** [cs01/pygdbmi#18]
When trying to install pygdbmi==0.7.4.2 I get the below error:

```
C:\> pip install pygdbmi
Collecting pygdbmi
  Using cached pygdbmi-0.7.4.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ago\AppData\Local\Temp\pip-build-j0g63a_a\pygdbmi\setup.py", line 5, in <module>
        from pygdbmi.tests import test_app
      File "C:\Users\ago\AppData\Local\Temp\pip-build-j0g63a_a\pygdbmi\pygdbmi\tests\test_app.py", line 14, in <module>
        from pygdbmi.gdbcontroller import GdbController, NoGdbProcessError
      File "C:\Users\ago\AppData\Local\Temp\pip-build-j0g63a_a\pygdbmi\pygdbmi\gdbcontroller.py", line 20, in <module>
        from ctypes.wintypes import HANDLE, DWORD, POINTER, BOOL
    ImportError: cannot import name 'POINTER'
```
```
C:\> python --version
Python 3.4.3
```

The previous version installs fine:

```
C:\> pip install pygdbmi==0.7.4.0
Collecting pygdbmi==0.7.4.0
  Downloading pygdbmi-0.7.4.0.tar.gz
Installing collected packages: pygdbmi
  Running setup.py install for pygdbmi ... done
Successfully installed pygdbmi-0.7.4.0
```

**Comment by cs01** [comment]
To be honest, Windows support has not been a first priority since I don't develop on Windows. 

It looks like 0.7.4.2 moved an import from a function to the global scope, which causes the error to be exposed at install time, rather than runtime. I think the bug was already there though. 

It's possible that 
```
 from ctypes.wintypes import HANDLE, DWORD, POINTER, BOOL
```
needs to be changed to 
```
 from ctypes import HANDLE, DWORD, POINTER, BOOL
```

Can you try that and let me know if it works? Otherwise, unfortunately, I will probably not be able to test this myself for a while.

**Comment by asgeroverby** [comment]
0.7.4.0 installs but does not work. It fails with a similar issue. 

`HANDLE` is not exposed from `ctypes` and `POINTER` is not exposed directly from `ctypes.wintypes`, however `LPDWORD` is, see below. The two unittests still fail due to an error in the subprocess communication, which I have now been able to fix.  

The subprocess communication error is:
```
OSError: [Errno 22] Invalid argument
```

My gdb might exit early?
https://stackoverflow.com/questions/23688492/oserror-errno-22-invalid-argument-in-subprocess

```
@@ -17,7 +17,7 @@ USING_WINDOWS = os.name == 'nt'
 if USING_WINDOWS:
     import msvcrt
     from ctypes import windll, byref, wintypes, WinError
-    from ctypes.wintypes import HANDLE, DWORD, POINTER, BOOL
+    from ctypes.wintypes import HANDLE, DWORD, LPDWORD, BOOL
 else:
     import fcntl

@@ -350,7 +355,6 @@ def _make_non_blocking(file_obj):
     http://stackoverflow.com/a/34504971/2893090"""
 
     if USING_WINDOWS:
-        LPDWORD = POINTER(DWORD)
         PIPE_NOWAIT = wintypes.DWORD(0x00000001)
 
         SetNamedPipeHandleState = windll.kernel32.SetNamedPipeHandleState
```

I will provide a fix if I find a solution for the subprocess communication.

**Comment by cs01** [comment]
I don't think gdb is exiting early, but I do think the Invalid argument error is because stdin/stdout/stderr the pipe is somehow invalid on windows. Have you tried skipping the call to `_make_non_blocking`, or tried anything else since your last comment?

**Comment by asgeroverby** [comment]
Yes, but without success. I'm unable to run interactive processes on windows using the subprocess module no matter what. I have thus resorted to running a series of batch scripts.  I'm unable to spend more time on a real solution currently.
