### ISSUE TITLE
output field 'payload' of command -thread-list-ids buggy

### ISSUE THREAD

**Issue by vivi00790** [cs01/pygdbmi#19]
Bug as below:   

![image](https://user-images.githubusercontent.com/6245453/30699979-d05e9324-9f18-11e7-8679-2b8c33b0295a.png)

According to [gdb document](https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI-Thread-Commands.html#GDB_002fMI-Thread-Commands), this command should list all threads id.   
I guess it's because all the keys of the ids of threads are 'thread-id', maybe your parser just updating the key, not adding a new key?

**Comment by cs01** [comment]
Great catch. You're right, the key is identical so the parser just overwrites it. I would consider this a gdb-mi bug. The payload should have this:
```
...
'thread-ids': ['1', '2']
...
```

I submitted a bug report to the gdb project: https://sourceware.org/bugzilla/show_bug.cgi?id=22217

**Comment by cs01** [comment]
I pushed a fix. The new output works around the gdb bug. Example output:

```json
   "payload": {
        "thread-ids": {
            "thread-id": [
                "1",
                "2"
            ]
        },
        "number-of-threads": "2",
        "current-thread-id": "2"
    },
```
