### ISSUE TITLE
No symbol table is loaded

### ISSUE THREAD

**Issue by paulorb** [cs01/pygdbmi#22]
```
response = gdbmi.write('-break-insert main')
>>> pprint(response)
[{'message': u'error',
  'payload': {u'msg': u'No symbol table is loaded.  Use the "file" command.'},
  'stream': 'stdout',
  'token': None,
  'type': 'result'}]´
```

I tried to use it with a simple application I am compiling the application using g++
g++ TestFileMonitor.cpp   -I./boost_1_55_0 -L./boost_1_55_0/stage/lib -l:libboost_thread.a -l:libboost_system.a -lpthread -g
If I try to debug it directly using gdb it works, if I use python (pygdbmi) it does not

```
#!/usr/bin/env python
from pygdbmi.gdbcontroller import GdbController
from pprint import pprint

# Start gdb process
gdbmi = GdbController()

# Load binary a.out and get structured response
response = gdbmi.write('-file-exec-file a.out')
pprint(response)
response = gdbmi.write('-break-insert main')
pprint(response)
response = gdbmi.write('next')
pprint(response)
response = gdbmi.exit()
```
Gdb version GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Ubuntu Version: Linux VirtualBox 3.19.0-25-generic #26 ~ 14.04.1 - Ubuntu SMP Fri Jul 24 21:18:00 UTC 2015 i686 i686 i686 GNU/Linux

**Comment by cs01** [comment]
Try "-file-exec-and-symbols" instead of "-file-exec-file"

**Comment by paulorb** [comment]
Great, tks I works!
