### ISSUE TITLE
timeout_sec is int in gdbcontroller.write but float in gdbcontroller.get_gdb_response 

### ISSUE THREAD

**Issue by vivi00790** [cs01/pygdbmi#24]
gdbcontroller.write is using timeout_sec as parameter of gdbcontroller.get_gdb_response when read_response flag is true
Why narrowed scope of timeout_sec  from float to int in gdbcontroller.write? What's the reason that gdbcontroller.write can't use float timeout_sec ?

**Comment by cs01** [comment]
It looks like the comment says it should be an int, but the code will accept float in the `write` method. I'll update the comment. Thanks!

**Comment by vivi00790** [comment]
well, I've tried using float like 0.1, the ide prompt warning said it should be int (using pycharm btw) so i just give it up, haven't actually run it, though.
i'll try and update result here, thanks for the reply

**Comment by cs01** [comment]
The value is passed into the `select` function. I looked up the documentation for that function and it says it takes a float, so it should be okay. Maybe pycharm parsed the docstring and warned you?

https://docs.python.org/2/library/select.html#select.select

**Comment by vivi00790** [comment]
yeah, i think you are right. after manually edited the docstring the warning dissappears, thanks! :)
also you might want to update your online documents, too, it still says timeout_sec is int

**Comment by cs01** [comment]
will do, thanks!

**Comment by cs01** [comment]
@vivi00790 fyi the docs have been updated
