### ISSUE TITLE
over-processed escape characters?

### ISSUE THREAD

**Issue by vivi00790** [cs01/pygdbmi#27]
in regular gdb, if I print a json, result:
![image](https://user-images.githubusercontent.com/6245453/34224393-aec38194-e5fd-11e7-9dcc-bafb0813a420.png)
in gdb with --interpreter=mi2 , if I print the same json, result:
![image](https://user-images.githubusercontent.com/6245453/34224420-d1f37656-e5fd-11e7-8ce1-db7b2d33d39b.png)
in pygdbmi , if I print  the same  json, result:
![image](https://user-images.githubusercontent.com/6245453/34224477-fc67d760-e5fd-11e7-8747-d2c0deb74a95.png)
so imo, the mi added escape characters in output stream automatically, and pygdbmi did it again
should I parse the payload twice (or three times 'cause origin string still contains \ and json parser won't accept it) to get correct json array string or is there any better way suggested?

**Comment by cs01** [comment]
Yikes that's a lot of escape characters.  I'll take a look when I get the time and get back to you.  Unfortunately it may be a while due to the holidays and travel, etc.  Thanks for filing the issue.

**Comment by vivi00790** [comment]
It's OK. Glad to help. Happy holidays :)

**Comment by cs01** [comment]
I believe I fixed this in 0.8.1.0, let me know what you think.

**Comment by vivi00790** [comment]
alright I've done some tests and here's the result:
commands for test:
python print "{\\"a\\":1}"
python print "{'id':1, 'cd':{'a':1, 'c':'b'}}"
python print '{"one" : "1", "two" : "2", "three" : "3"}'
![image](https://user-images.githubusercontent.com/6245453/35071891-5d3b7dc8-fc1d-11e7-9908-324e4bbe0c0d.png)

for the first command, it seems that gdb or pygdbmi still messed on parse python escape chars
the second command is illegal json, but works fine
the third command leads to a weird result, seems gdb or pygdbmi tends to parse the \ again

here are also some tests on escape chars:
python print '\\\\//\\/'  
python print '\\"\\'\\\\'
![image](https://user-images.githubusercontent.com/6245453/35072142-5231c044-fc1e-11e7-8676-fe000b09839e.png)

**Comment by vivi00790** [comment]
btw I solved my own problem using the third command by 
decoded_string = bytes(myString, "utf-8").decode("unicode_escape")
Thank you 
just want to told you the crazy escape chars I found
Thank you 
Thank you 
Thank you
