### ISSUE TITLE
new behavior when running "run" command in GDB 8.1

### ISSUE THREAD

**Issue by vivi00790** [cs01/pygdbmi#33]
In GDB 8.1, it seems when running "run" related command under MI, GDB will split output into two part and causing pygdbmi only catch the former part.
![tempsnip](https://user-images.githubusercontent.com/6245453/40370661-54910bb8-5e13-11e8-883b-afd7b0e80699.png)
I've tried calling get_gdb_response() just after run command, it works at first "run", but whenever I call "run" again to restart program will raise GdbTimeOutError.
I'll post raw GDB MI output and pygdbmi output here, hope it helps.
First "run" in GDB:
![image](https://user-images.githubusercontent.com/6245453/40372146-acae50b4-5e16-11e8-9146-35883b4b617b.png)
Second "run" in GDB:
![image](https://user-images.githubusercontent.com/6245453/40372212-d23dba72-5e16-11e8-8f7b-5332026f76a7.png)
First "run" with pygdbmi:
![image](https://user-images.githubusercontent.com/6245453/40372304-f26df6ea-5e16-11e8-833c-876db224e9a3.png)
Notice here pygdbmi catch breakpoint stopped event:
![image](https://user-images.githubusercontent.com/6245453/40372353-0f88d786-5e17-11e8-9486-4ec18d0e7949.png)
![image](https://user-images.githubusercontent.com/6245453/40372383-237083f2-5e17-11e8-9f2e-e4ba30461848.png)
![image](https://user-images.githubusercontent.com/6245453/40372406-32a208a0-5e17-11e8-943f-befbc0a0c391.png)
Second "run" with pygdbmi:
Trying to fetch second part causing timeout, and pygdbmi will never catch breakpoint stopped event.  
![image](https://user-images.githubusercontent.com/6245453/40372568-93a30bf4-5e17-11e8-9bf5-cbdd2405a4b5.png)
![image](https://user-images.githubusercontent.com/6245453/40372694-cb805b3a-5e17-11e8-927e-b355011dce61.png)
![image](https://user-images.githubusercontent.com/6245453/40372803-0c37b39e-5e18-11e8-8b54-fbff1e731198.png)

**Comment by cs01** [comment]
Can you add more context on how you are running this? Are you using GdbController? If so, how are you running it? This seems like something you can might be able to fix by adjusting your scripts or passing different flags when using the gdb controller. But I might not be understanding.

This documentation may help: https://grassfedcode.com/pygdbmi/api/pygdbmi.html#module-pygdbmi.gdbcontroller

**Comment by vivi00790** [comment]
Yes I'm using GdbController, here's my statement:
`self.gdbmi = GdbController(gdb_args=['--quiet', '--interpreter=mi2', debugee_name])`
and all commands go through the `write()` function
I've read the doc you provided and tried to adjust `time_to_check_for_additional_output_sec` to 2 and it works. 
I'll try lower it if I have time, 2 sec block is a bit annoying.  
Thank you :)
