### ISSUE TITLE
interrupt_gdb terminates gdb [win]

### ISSUE THREAD

**Issue by veeman** [cs01/pygdbmi#42]
Im currently facing an issue where gdb silently terminates when i execute `interrupt_gdb()`.
I think it's a windows and or gdb version related problem. It's very annoying because i can not halt the target. 

**System**: Windows 10
**Gdb**: GNU gdb (GNU Tools for ARM Embedded Processors) 7.10.1.20160616-cvs
**pygdbmi**: v0.9.0.3

```python
from pygdbmi.gdbcontroller import GdbController

gdbmi = GdbController(gdb_path="arm-none-eabi-gdb")

gdbmi.write("symbol-file application.axf")
gdbmi.write("-target-select remote localhost:2331")
gdbmi.write("-exec-continue")
gdbmi.interrupt_gdb()
gdbmi.write("-exec-continue")
```

The last command yields to the following exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python-3.6.6.amd64\lib\site-packages\pygdbmi\gdbcontroller.py", line 204, in write
    self.verify_valid_gdb_subprocess()
  File "python-3.6.6.amd64\lib\site-packages\pygdbmi\gdbcontroller.py", line 180, in verify_valid_gdb_subprocess
    % str(self.gdb_process.poll())
pygdbmi.gdbcontroller.NoGdbProcessError: gdb process has already finished with return code: 2
```

Any ideas how to solve this?

**Comment by veeman** [comment]
I found a workaround. I put gdb simple in async mode and execute the interrupt command explicitly.

```python
from pygdbmi.gdbcontroller import GdbController

gdbmi = GdbController(gdb_path="arm-none-eabi-gdb")

gdbmi.write("-gdb-set target-async on")

gdbmi.write("symbol-file application.axf")
gdbmi.write("-target-select remote localhost:2331")

gdbmi.write("-exec-continue")
gdbmi.write("-exec-interrupt")
# gdbmi.interrupt_gdb()
gdbmi.write("-exec-continue")
```

I will close this issue here, because it is not really a pygdbmi issue.

Maybe related; other tools have also their problems with arm-none-eabi-gdb and sigint: https://github.com/microsoft/vscode-cpptools/issues/833

**Comment by Pardeep25** [comment]
I am facing this issue while using ntoaarch64-gdb.exe
