### ISSUE TITLE
Version of code descrepancy?

### ISSUE THREAD

**Issue by SourceCodeDeleted** [cs01/pygdbmi#48]
Salutations,

Firstly awesome project. 

I am still investigating this issue as it appears to be odd.

To the issue, I was noticing that **nexti** commands weren't always  handled the same when I saw odd skips in certain places in a program. I noticed some oddity where **nexti** on **mov ebp, esp** was resulting the program running past the  next instruction.

Anyway, I thought to look and see if I was supposed to perform the **next** . I looked at the example code and there is the command    ` responses = gdbmi.write("-exec-next")`  This appears to now be removed from the code? 

Is this command supposed to handle next differently ? Should it be ok to just call **nexti** as  ` responses = gdbmi.write("nexti")`

**Comment by cs01** [comment]
I am really sorry, but I don't have time to look into this. If you found a bug and a fix, a PR is welcome. And of course if anyone else reading is inclined to investigate, help is always appreciated.

**Comment by SourceCodeDeleted** [comment]
I understand and appreciate your honesty. I shall continue to look my self and see if there is something I can do about this.

**Comment by SourceCodeDeleted** [comment]
Hello , I am sorry to bother you, and I understand you don't have time. Perhaps maybe you can point on to where the problem might exist.

I noticed other commands like delete don't appear to work. I thought to try a break on EIP  then using nexti kind of works.

It seems like there is a disconnect or mis communication between the GDB and PyGDBMI . More in particularly in the managerIO.py section of things because I can see that **self.io_manager.write** is receiving the correct commands. It is somewhat difficult to check there but still working on it.

**Comment by SourceCodeDeleted** [comment]
There is a deeper problem with this and it appears to be in the end with GDB and the MI interface. GDB itself doesn't struggle but I experience the same issues in the MI . I thought I earlier tested this and there weren't problems .

I will close this.

Thank you.
