### ISSUE TITLE
Support OSX by using alternative to epoll()

### ISSUE THREAD

**Issue by felipesere** [cs01/pygdbmi#5]
I came here through https://github.com/cs01/gdbgui/ which looks brilliant.

My problem is that I do all my Rust development in OSX, which does not support epoll().
https://github.com/cs01/pygdbmi/blob/master/pygdbmi/gdbcontroller.py#L79

Maybe have a look at this file from py-prefork-server?
https://github.com/crustymonkey/py-prefork-server/blob/ff9c1411f27843c6384d6c5b2dfcc2c09d4642bf/preforkserver/poller.py

**Comment by cs01** [comment]
Hi thanks for you interest! I have have a few requests for OSX, and I would love to support it. I don't own a mac, so I can't really test and be sure things are working. I tried to test for OSX on the travis buildserver, but it's still in beta and doesn't work yet. My concern is that if I remove epoll to try and get this compatible with OSX, I will hit another wall with some other library. If I can get pygdbmi working without epoll, would you be open to testing a branch for me, and doing subsequent testing on any future issues that come up?

**Comment by felipesere** [comment]
For sure! I was trying to whack the `poller.py` into pygdbmi myself but failed at the KQueue interface. If you point me to a branch, I'll pull and test it 👍

**Comment by rakeshmane** [comment]
Same problem here. Please add support for OSX.

**Comment by ssokolow** [comment]
@felipesere KQueue is the FreeBSD-only equivalent to `epoll`. (When `select` proved not fast enough for servicing tends of thousands of connections from the same server, each OS came up with its own successor and POSIX was never updated to re-unify them.)

If you're just watching `stdin`, `stdout`, and `stderr`, then you're basically operating in the ideal conditions for using `select` (a mere three FDs, all bunched in the lowest FD numbers you can get) and the use of Python will become a performance problem long before the use of `select` will.

Just replace calls like `self.epoll.register(self.gdb_process.stdout.fileno(), select.EPOLLIN)` with appending the `fileno` to a Python list and then replace `events = self.epoll.poll(timeout_sec)` with calls to `rlist_read, wlist_read, xlist_read = select.select(rlist, wlist, xlist, timeout_sec)`.

**Comment by ssokolow** [comment]
Apparently the simplest POSIX/Win32-portable way to do it using the Python stdlib is to use one thread for each thing you want to listen on, a threadsafe queue, and blocking reads/writes. That, too, shouldn't be a big deal for performance if you're only listening on three FDs.

Here's a [StackOverflow answer with example code](http://stackoverflow.com/a/4896288/435253).

**Comment by cs01** [comment]
You guys rock, thanks for the help with this!
