### ISSUE TITLE
Thank you! I ported your parser to Rust

### ISSUE THREAD

**Issue by danielzfranklin** [cs01/pygdbmi#52]
Hi, I just wanted say thank you. I ported your parser to rust for [a project](https://github.com/danielzfranklin/gdbmi) and it's been working beautifully. I hope you don't mind me opening an issue to say this.

**Comment by cs01** [comment]
Thanks for sharing, that’s awesome! I considered doing this to learn rust but never found the time.

There should be a way to call rust from Python. I would love to call into your parser from pygdbmi, since parsing with Python can be a bottleneck.

**Comment by danielzfranklin** [comment]
I can look into that. I'm currently technically supposed to be doing finals, so I can't promise promptness :)

My current architecture has a worker that reads from stderr/stdout and also from a channel of messages to send to gdb over stdin. Then there's a frontend that takes commands from the user and sends them to the worker over the channel, and receives the matching replies back when worker gets them. So the actual io is single threaded, but you can send a command while waiting for the result of another (unless it's a console command).

In theory I think that makes sense, but I haven't tried it on any real world data yet. I'm definitely interested if you have any good ideas for benchmarks/what's been a performance issue for you.

I think it's be pretty easy to write python bindings for the parser bit, since it's a synchronous function that takes a string a returns a simple-ish type. In theory [it seems possible](https://pyo3.rs/v0.13.2/ecosystem/async-await.html) to call async rust code from python, so we could also build that.

I noticed in another issue you were considering rewriting the backend server. It might be easier for me to write a Rust server frontend than to have python sit in front of it. On the other hand you might prefer more of the code to be in a language you're comfortable with.

What do you think?

**Comment by cs01** [comment]
If I’m being honest with myself, I don’t really have the time to devote to these projects (pygdbmi and gdbgui) other than maintenance. And I’d be hesitant to adopt any major rewrite since the projects are pretty complex and are stable. I am excited at the idea of an ffi into Rust, but it’s probably best to just leave it alone. Even if it were working, installation becomes an issue because the person installing it will need to be able to compile rust for their platform (I think?).

**Comment by danielzfranklin** [comment]
That all makes sense. I doubt there'd be a huge speedup anyway since it's io bound. Feel free to close this issue.

**Comment by cs01** [comment]
I think there could absolutely be a speed up in the non-io bound stuff. Rust is way faster than Python. IIRC the unit tests ensure the parsing is done in o(n) time. If they don’t currently they definitely used to. 

There was a pull request a while back where large strings were parsed more quickly by taking advantage of some implementation details of Python. 

Anyway, thanks for sharing and good luck on your finals.
