### ISSUE TITLE
Incompatible behavior in GDB command line and pygdbmi

### ISSUE THREAD

**Issue by qtmlr** [cs01/pygdbmi#53]
**Is your feature request related to a problem? Please describe.**
I have an example program that printf's a variable i in a fixed loop from 0 to 3.
When I run the same in GDB as:
`gdb --interpreter=mi3 a.out`
`-break-insert main`
`-exec-run`
then repeatedly do `-exec-step`

This way I can see the `stdout` of my small test program with the MI3 messages intermixed, all fitting to the program flow.

I see no way to achieve the same in `pygdbmi`.  The output of my program is only seen after it exits.  So I can first see the program flow and after that I can see the output, but I can't link this to the program flow any more.

**Describe the solution you'd like**
This behavior is the behavior of `gdb` itself, when doing `subprocess.Popen` on `gdb` and doing the same steps, I can see the same behavior.  So I don't think this is a bug of `pygdbmi`.  gdb outputs the data this way.  But the behavior does not help, some compatibility way would help, or any other way to link the output to the lines that produced them.  If I run the same program in a `/bin/bash` or using `pygdbmi`, I see different behavior.

**Describe alternatives you've considered**
I tried `subprocess.Popen` in an own script but got the same behavior.

**Additional context**
I run gdb-10.1 on Linux

My test program is:
`#include "stdio.h"`
`#include "stdlib.h"`

`void fct(void) {`
`    for(int i = 0; i < 3; i++) {`
`        printf("i %d\n", i);`
`    }`
`}`

`int main(int argc, char** argv) {`
`    printf("Hi there\n");`

`    fct();`

`    return EXIT_SUCCESS;`
`}`

**Comment by cs01** [comment]
Yeah that is a tricky thing that comes up. There is a workaround that might work for you. You can redirect the program's i/o to a file or to a different tty. Check out https://sourceware.org/gdb/onlinedocs/gdb/Input_002fOutput.html.

**Comment by qtmlr** [comment]
Great, Thanks for your hint!
