### ISSUE TITLE
Escapes in MI error records are mangled

### ISSUE THREAD

**Issue by barisione** [cs01/pygdbmi#57]
**Describe the bug**

When parsing an error record, backslashes are just dropped. This works for quotes but mangles other escapes (like `\n`).

For instance this:
```
^error,msg="This is an error\non multiple lines and with\tother escapes"
```
Becomes a dictionary with this message:
```
This is an errornon multiple lines and withtother escapes
```

**To Reproduce**

I wrote a simple `script.py` Python script with a GDB command to be able to have arbitrary escapes:
```
import gdb


class MyCommand(gdb.Command):
    def __init__(self):
        super().__init__("my-command", gdb.COMMAND_NONE)

    def invoke(self, args, from_tty):
        raise gdb.GdbError("This is an error\non multiple lines and with\tother escapes")


MyCommand()
```

Start GDB in MI-mode and load the script:
```
gdb -i=mi2 -x script.py
```

When you use the command, GDB produces this output:
```
(gdb)
my-command
&"my-command\n"
&"This is an error\n"
&"on multiple lines and with\tother escapes\n"
^error,msg="This is an error\non multiple lines and with\tother escapes"
```

Parse it with `pygdbmi`:
```
gdbmiparser.parse_response(r'^error,msg="This is an error\non multiple lines and with\tother escapes"')
```
And you get:
```
{'type': 'result',
 'message': 'error',
 'payload': {'msg': 'This is an errornon multiple lines and withtother escapes'},
 'token': None}
```

**Expected behavior**

Escapes should be interpreted. In the example above I would expect this output:
```
{'type': 'result',
 'message': 'error',
 'payload': {'msg': 'This is an error\non multiple lines and with\tother escapes'},
 'token': None}
```

The correct escape behaviour (which is not compatible with Python escapes) can be found in `printchar` in `gdb/utils.c` in the binutils-gdb repository.

**Please complete the following information:**
* OS: macOS
* pygdbmi version (`pip freeze` output):
```
$ pip freeze | grep pygdbmi
pygdbmi==0.10.0.1
```

**Additional context**

I haven't looked at the pygdbmi code yet but I may be able to make a PR if you are interested. I already have an unescape function in Python.

**Comment by cs01** [comment]
Thanks for the report. Yes if you'd like to make a PR that would be appreciated!

**Comment by barisione** [comment]
> Thanks for the report. Yes if you'd like to make a PR that would be appreciated!

Here we go: https://github.com/cs01/pygdbmi/pull/59 (not sure if you receive notifications for PRs).

**Comment by cs01** [comment]
Thanks, yes I do. I appreciate the PR. I’ll review it as soon as possible. I have a lot of obligations in my personal life at the moment but I will get to it within the next 7 days.
