### ISSUE TITLE
get_gdb_response doesn't parse tab char correctly

### ISSUE THREAD

**Issue by brianignacio5** [cs01/pygdbmi#62]
**Describe the bug**

**To Reproduce**
Using GDBController's `write('-data-disassemble -s addr -e addr -- 5', read_response=False)`and `get_gdb_response` to read  instructions is converting `\t` tabs characters into `t` instead of spaces or the tab character. 

**Expected behavior**
For example `call8t0x42005600` is received  instead of  `call8\t0x42005600` or  `call8    0x42005600`

**Screenshots**

**Please complete the following information:**
* OS: Windows 11
* pygdbmi version (`pip freeze` output):  0.9.0.2

**Additional context**

**Comment by barisione** [comment]
This may be caused by https://github.com/cs01/pygdbmi/issues/57 / https://github.com/cs01/pygdbmi/issues/58 which I haven't released yet.
Any chance you can try with `pygdbmi` from `master`?

**Comment by cs01** [comment]
@barisione do you have any plans to make a release?

**Comment by brianignacio5** [comment]
Sorry for late reply. Yes it does seems to be fixed with master @barisione 

Same as @cs01 , any release plan ?

**Comment by barisione** [comment]
I tried making a release but I couldn't get it to work. I emailed @cs01 for help and I will make one as soon as we figure out what's wrong.

**Comment by barisione** [comment]
Thanks to @cs01 I figured out was was going wrong (`twine` was not being helpful and was printing no error messages, even with `--verbose`!) and I made a release.

**Comment by cs01** [comment]
Thanks for making the release!
