### ISSUE TITLE
README.md - AttributeError: 'GdbController' object has no attribute 'get_subprocess_cmd'

### ISSUE THREAD

**Issue by ololuki** [cs01/pygdbmi#69]
Example from README.md does not work.

Running gdbmi.get_subprocess_cmd() cause following error:
AttributeError: 'GdbController' object has no attribute 'get_subprocess_cmd'

Function get_subprocess_cmd() was removed from file pygdbmi/gdbcontroller.py in commit:
449080a#diff-e29bd3c69c0c2b3f6f7c89a6ea177b322af7411076e74606faddf68573a7630dL126

Please update README.md

pygdbmi version (pip freeze output):
pygdbmi 0.10.0.2

**Comment by barisione** [comment]
Thanks for reporting! I will try to fix this in time for the next release.
