### ISSUE TITLE
-break-insert   *  address  not supported

### ISSUE THREAD

**Issue by suning2012** [cs01/pygdbmi#94]
**(gdb)  -break-insert * 0x44a920**
^error,msg="-break-insert: Garbage following <location>"

**(gdb) break * 0x44a920**
&"break * 0x44a920\n"
~"Breakpoint 1 at 0x44a920\n"
=breakpoint-created,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x000000000044a920",thread-groups=["i1"],times="0",original-location="* 0x44a920"}
^done
(gdb)

**Comment by barisione** [comment]
Hi @suning2012. The problem is the extra space between the asterisk and the address (and it's not related to pygdmi):
```
(gdb)
-break-insert * 0x555555555169
^error,msg="-break-insert: Garbage following <location>"
(gdb)
-break-insert *0x555555555169
^done,bkpt={number="4",type="breakpoint",disp="keep",enabled="y",addr="0x0000555555555169",func="main",file="test-hello-world.c",fullname="/data/bari/src/Test/test-hello-world.c",line="5",thread-groups=["i1"],times="0",original-location="*0x555555555169"}
```

Please reopen if I misunderstood your report.
